# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import project3_pb2 as project3__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in project3_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateItem = channel.unary_unary(
                '/MarketService/CreateItem',
                request_serializer=project3__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=project3__pb2.CreateItemResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/MarketService/GetItem',
                request_serializer=project3__pb2.GetItemRequest.SerializeToString,
                response_deserializer=project3__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.SearchItems = channel.unary_unary(
                '/MarketService/SearchItems',
                request_serializer=project3__pb2.SearchItemsRequest.SerializeToString,
                response_deserializer=project3__pb2.SearchItemsResponse.FromString,
                _registered_method=True)
        self.UpdateItem = channel.unary_unary(
                '/MarketService/UpdateItem',
                request_serializer=project3__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=project3__pb2.UpdateItemResponse.FromString,
                _registered_method=True)
        self.PlaceBid = channel.unary_unary(
                '/MarketService/PlaceBid',
                request_serializer=project3__pb2.PlaceBidRequest.SerializeToString,
                response_deserializer=project3__pb2.PlaceBidResponse.FromString,
                _registered_method=True)
        self.JoinAuction = channel.stream_stream(
                '/MarketService/JoinAuction',
                request_serializer=project3__pb2.AuctionClientMessage.SerializeToString,
                response_deserializer=project3__pb2.AuctionServerMessage.FromString,
                _registered_method=True)


class MarketServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceBid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinAuction(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=project3__pb2.CreateItemRequest.FromString,
                    response_serializer=project3__pb2.CreateItemResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=project3__pb2.GetItemRequest.FromString,
                    response_serializer=project3__pb2.GetItemResponse.SerializeToString,
            ),
            'SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItems,
                    request_deserializer=project3__pb2.SearchItemsRequest.FromString,
                    response_serializer=project3__pb2.SearchItemsResponse.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=project3__pb2.UpdateItemRequest.FromString,
                    response_serializer=project3__pb2.UpdateItemResponse.SerializeToString,
            ),
            'PlaceBid': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceBid,
                    request_deserializer=project3__pb2.PlaceBidRequest.FromString,
                    response_serializer=project3__pb2.PlaceBidResponse.SerializeToString,
            ),
            'JoinAuction': grpc.stream_stream_rpc_method_handler(
                    servicer.JoinAuction,
                    request_deserializer=project3__pb2.AuctionClientMessage.FromString,
                    response_serializer=project3__pb2.AuctionServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MarketService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MarketService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MarketService/CreateItem',
            project3__pb2.CreateItemRequest.SerializeToString,
            project3__pb2.CreateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MarketService/GetItem',
            project3__pb2.GetItemRequest.SerializeToString,
            project3__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MarketService/SearchItems',
            project3__pb2.SearchItemsRequest.SerializeToString,
            project3__pb2.SearchItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MarketService/UpdateItem',
            project3__pb2.UpdateItemRequest.SerializeToString,
            project3__pb2.UpdateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceBid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MarketService/PlaceBid',
            project3__pb2.PlaceBidRequest.SerializeToString,
            project3__pb2.PlaceBidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinAuction(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/MarketService/JoinAuction',
            project3__pb2.AuctionClientMessage.SerializeToString,
            project3__pb2.AuctionServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServiceNodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/ServiceNodeService/Heartbeat',
                request_serializer=project3__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=project3__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.HandleCreate = channel.unary_unary(
                '/ServiceNodeService/HandleCreate',
                request_serializer=project3__pb2.CreateRequest.SerializeToString,
                response_deserializer=project3__pb2.CreateResponse.FromString,
                _registered_method=True)
        self.HandleGet = channel.unary_unary(
                '/ServiceNodeService/HandleGet',
                request_serializer=project3__pb2.GetRequest.SerializeToString,
                response_deserializer=project3__pb2.GetResponse.FromString,
                _registered_method=True)
        self.HandleSearch = channel.unary_unary(
                '/ServiceNodeService/HandleSearch',
                request_serializer=project3__pb2.SearchRequest.SerializeToString,
                response_deserializer=project3__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.HandleUpdate = channel.unary_unary(
                '/ServiceNodeService/HandleUpdate',
                request_serializer=project3__pb2.UpdateRequest.SerializeToString,
                response_deserializer=project3__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.HandleStoreBid = channel.unary_unary(
                '/ServiceNodeService/HandleStoreBid',
                request_serializer=project3__pb2.StoreBidRequest.SerializeToString,
                response_deserializer=project3__pb2.StoreBidResponse.FromString,
                _registered_method=True)
        self.HandleAuction = channel.unary_unary(
                '/ServiceNodeService/HandleAuction',
                request_serializer=project3__pb2.ChangeAuctionRequest.SerializeToString,
                response_deserializer=project3__pb2.ChangeAuctionResponse.FromString,
                _registered_method=True)


class ServiceNodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleStoreBid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleAuction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=project3__pb2.HeartbeatRequest.FromString,
                    response_serializer=project3__pb2.HeartbeatResponse.SerializeToString,
            ),
            'HandleCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleCreate,
                    request_deserializer=project3__pb2.CreateRequest.FromString,
                    response_serializer=project3__pb2.CreateResponse.SerializeToString,
            ),
            'HandleGet': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleGet,
                    request_deserializer=project3__pb2.GetRequest.FromString,
                    response_serializer=project3__pb2.GetResponse.SerializeToString,
            ),
            'HandleSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleSearch,
                    request_deserializer=project3__pb2.SearchRequest.FromString,
                    response_serializer=project3__pb2.SearchResponse.SerializeToString,
            ),
            'HandleUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleUpdate,
                    request_deserializer=project3__pb2.UpdateRequest.FromString,
                    response_serializer=project3__pb2.UpdateResponse.SerializeToString,
            ),
            'HandleStoreBid': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleStoreBid,
                    request_deserializer=project3__pb2.StoreBidRequest.FromString,
                    response_serializer=project3__pb2.StoreBidResponse.SerializeToString,
            ),
            'HandleAuction': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleAuction,
                    request_deserializer=project3__pb2.ChangeAuctionRequest.FromString,
                    response_serializer=project3__pb2.ChangeAuctionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ServiceNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ServiceNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceNodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServiceNodeService/Heartbeat',
            project3__pb2.HeartbeatRequest.SerializeToString,
            project3__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServiceNodeService/HandleCreate',
            project3__pb2.CreateRequest.SerializeToString,
            project3__pb2.CreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServiceNodeService/HandleGet',
            project3__pb2.GetRequest.SerializeToString,
            project3__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServiceNodeService/HandleSearch',
            project3__pb2.SearchRequest.SerializeToString,
            project3__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServiceNodeService/HandleUpdate',
            project3__pb2.UpdateRequest.SerializeToString,
            project3__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleStoreBid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServiceNodeService/HandleStoreBid',
            project3__pb2.StoreBidRequest.SerializeToString,
            project3__pb2.StoreBidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleAuction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServiceNodeService/HandleAuction',
            project3__pb2.ChangeAuctionRequest.SerializeToString,
            project3__pb2.ChangeAuctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/StorageService/Heartbeat',
                request_serializer=project3__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=project3__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/StorageService/Create',
                request_serializer=project3__pb2.CreateRequest.SerializeToString,
                response_deserializer=project3__pb2.CreateResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/StorageService/Get',
                request_serializer=project3__pb2.GetRequest.SerializeToString,
                response_deserializer=project3__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/StorageService/Search',
                request_serializer=project3__pb2.SearchRequest.SerializeToString,
                response_deserializer=project3__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/StorageService/Update',
                request_serializer=project3__pb2.UpdateRequest.SerializeToString,
                response_deserializer=project3__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.StoreBid = channel.unary_unary(
                '/StorageService/StoreBid',
                request_serializer=project3__pb2.StoreBidRequest.SerializeToString,
                response_deserializer=project3__pb2.StoreBidResponse.FromString,
                _registered_method=True)
        self.ChangeAuction = channel.unary_unary(
                '/StorageService/ChangeAuction',
                request_serializer=project3__pb2.ChangeAuctionRequest.SerializeToString,
                response_deserializer=project3__pb2.ChangeAuctionResponse.FromString,
                _registered_method=True)


class StorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreBid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeAuction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=project3__pb2.HeartbeatRequest.FromString,
                    response_serializer=project3__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=project3__pb2.CreateRequest.FromString,
                    response_serializer=project3__pb2.CreateResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=project3__pb2.GetRequest.FromString,
                    response_serializer=project3__pb2.GetResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=project3__pb2.SearchRequest.FromString,
                    response_serializer=project3__pb2.SearchResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=project3__pb2.UpdateRequest.FromString,
                    response_serializer=project3__pb2.UpdateResponse.SerializeToString,
            ),
            'StoreBid': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreBid,
                    request_deserializer=project3__pb2.StoreBidRequest.FromString,
                    response_serializer=project3__pb2.StoreBidResponse.SerializeToString,
            ),
            'ChangeAuction': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeAuction,
                    request_deserializer=project3__pb2.ChangeAuctionRequest.FromString,
                    response_serializer=project3__pb2.ChangeAuctionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('StorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StorageService/Heartbeat',
            project3__pb2.HeartbeatRequest.SerializeToString,
            project3__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StorageService/Create',
            project3__pb2.CreateRequest.SerializeToString,
            project3__pb2.CreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StorageService/Get',
            project3__pb2.GetRequest.SerializeToString,
            project3__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StorageService/Search',
            project3__pb2.SearchRequest.SerializeToString,
            project3__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StorageService/Update',
            project3__pb2.UpdateRequest.SerializeToString,
            project3__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreBid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StorageService/StoreBid',
            project3__pb2.StoreBidRequest.SerializeToString,
            project3__pb2.StoreBidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeAuction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StorageService/ChangeAuction',
            project3__pb2.ChangeAuctionRequest.SerializeToString,
            project3__pb2.ChangeAuctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
